spring:
  datasource:
    url: jdbc:mysql://localhost:3306/public?useUnicode=true&serverTimezone=UTC

#    name: root
#    password: 1234
    hikari:
      username: root
      password: root
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
#  flyway:

