spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=UTC

#    name: root
#    password: 1234
    hikari:
      username: root
      password: 1234
      connection-test-query: SELECT 1 FROM contacts
  h2:
    console:
      enabled: true
